### PR TITLE
Freshen Dockerfile

### PR DESCRIPTION
**Pull request by damienleger**
- use last alpine image
- use last kubectl cli
- remove unnecessary make package

### CODE REVIEW

**Comment by bboreham** [comment]
Yes, I believe kubectl 1.9 stopped working with v1.5 servers.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#principles:

> We currently only guarantee one release of version skew is supported, but we strive to make old releases of kubectl continue to work with newer servers in compliance with our API compatibility guarantees.

**Comment by rade** [comment]
Wouldn't it be prudent to bump kubectl to a less recent version, to retain better compatibility with older k8s?

1.11.x, perhaps?

**Comment by andrebriggs** [comment]
@rade what is the minimum version of Kubernetes server you want to support? 

@damienleger any update?

**Comment by bboreham** [comment]
In view of no update, I'll push a commit moving it to 1.11.9

**Pull request merged**
